@extends('template.app')
@section('content')

    <h2>Faq</h2>
    <p>
    <h3>Q: What is is a MTKT Capital Merchant Cash Advance?</h3><p>
        A: MTKT Capital Cash Advance is a convenient alternative used by thousands of small business owners much like yourself to finance their working capital needs. MTKT Capital provides working capital to help you run your business, whether you’re expanding , purchasing inventory, advertising, or even in an emergency - in fact you are able to use the money for any one of your business needs. A MTKT Capital Cash Advance is not a business loan. Approval is based on your business history not some singular score, such as credit or FICO score. We give you cash upfront in exchange for an agreed upon percentage of your future income.  This is called factoring based on your account receivables.</p><h3>Q: How can my business qualify?</h3><p>
        A: Your business must process at least $2,000 per month in credit card sales, or deposit at least $10,000 per month in a bank, and have no open bankruptcy. That’s all you need to qualify!</p><h3>Q: How long do I have to be in business?</h3><p>
        A: Typically for a minimum of 6 months but this is flexible depending on your business.</p><h3>Q: How much working capital can I obtain for my business?</h3><p>
        A: MTKT Capital will provide your business up to $500,000 (much more in some cases) in working capital! The minimum advance we offer is typically $5000.</p><h3>Q: How do you determine how much I can qualify for?</h3><p>
        A: With our merchant cash advance program you can receive an advance of up to 200% of your average monthly major credit card sales and up to 50% of overall bank deposits. For example, a business that processes an average of $20,000 per month can qualify for up to $40,000 in working capital.</p><h3>Q: What is the interest rate?</h3><p>
        A:That’s the beautiful thing about a Merchant Cash Advance, there is no interest rate! It’s an advance, not a loan. We charge a one-time flat fee for the money in exchange for your future credit card receivables or banks deposits. The advance gets paid back as a percentage of your sales each time you batch out until the entire amount is satisfied. This is called Factoring.</p><h3>Q: How fast is the underwriting process? </h3><p>
        A: One of the main benefits of our MTKT Capital merchant cash advance is how quickly we can provide working capital to your business. With proper documentation, we can provide an approval on your application within 24-48 hours and we can wire you the funds within 3-5 business days!</p><h3>Q: What documentation do you require to get a merchant approved? </h3><p>
        A: The process is simple. We require:</p><p>
        1.) A short 1 page application</p><p>
        2.) Four most recent bank statement, all pages.</p><p>
        3.) Four most recent credit card processing statement, all pages.</p><p>
        4.) Copy of drivers license</p><p>
        5.) Business License</p><p>
        6.) Voided Business check</p><h3>Q: What are the credit requirements?  </h3><p>
        A: This is one of the main areas we differ from a bank loan. Since there is no personal guarantee we don’t require that you have a certain credit score. Bad credit is not a problem. Even tax liens are OK with an explanation or payment plan. All we ask is that you have no open bankruptcies to be eligible.</p><h3>Q: Are there any other any other credit or lease requirements? </h3><p>
        A: Business owners must either own their location or have at least one year left on their lease.</p><h3>Q: How do I pay back the advance? </h3><p>
        A: Payback of the advance is made through an automated deduction of an agreed upon percentage of your net settled credit card sales until the purchased price is satisfied or we use an ACH to pull the funds directly from a business bank account. The process is automated and seamless so when you “batch” out your credit and debit card sales (typically daily), your processor will automatically forward the agreed upon percentage of those sales to us. The best part with our program is that there is no fixed payments! Since payments to us are based upon a fixed percentage of your sales, if your sales go up you pay back the advance faster and if your sales are down, the advance is paid back a bit slower. We only get paid when you get paid. This helps you to better manage your cash flow. Everything is automatic so you never have to worry about writing checks, making monthly payments, late payments or escalating interest rates like you would with a bank.</p><h3>Q:What is the daily withholding percentage taken out of my business’ credit card batch? </h3><p>
        A: We typically will take between 10-30% when you settle out nightly to pay-back the advance. The percentage can be a little higher or lower depending on your business’ overall cash flow and also will be based upon how much capital you are looking for.</p><h3>Q: What are the application fees? </h3><p>A: There is no fee to apply for the program. </p><h3>Q: How soon after my first advance can I obtain another advance? </h3><p>A: You will be eligible for a renewal opportunity once you have paid back 50-60% of their current advance. The majority of our merchants renew for additional working capital at least once a year.</p><h3>Q: What business types work best with the merchant cash advance programs? </h3><p>A: Restaurants, bars, medical offices, seasonal businesses, clothing stores, liquor stores, spas, hair/nail/tanning salons, dry cleaners, bookstores, music stores, accessories, gift/stationary stores, coffee shops, eyeglass stores, hosiery stores, beauty shops, movie theaters, parking garages, sporting goods stores, florists, and gourmet/ specialty food stores.<br><br>We can provide most businesses with funding. Give us a call and we can discuss your options.</p><h3>Q: Which Which business business type types are prohibited are prohibited under your programs</h3><p> A: Sorry we don’t fund pornographic shops, escort services, gambling services, or tattoo parlors. </p>    </p>

@stop