@extends('template.app')
@section('content')

    <h2>Privacy Policy</h2>
    <p>
        <ul>
            <li>Information We Collect<p>We collect information required to verify your identity, to determine whether or not you qualify for one of our loan products, and to process your account including deducting automatic payments. We collect information that includes your bank statements, credit card statements, your average bank balance, personal and business credit history, tax ID number, social security number, bank account information and payment behavior. We may conduct a site visit to collect information. We also obtain your credit score from the three credit bureaus. Once you are an MTKT Capital customer, we may reach out to you for information again if you decide to renew your loan.</p></li><hr>
    <li>Privacy and Sharing of Information<p>By providing us the required information as outlined above and in your application, you are granting OnDeck and our trusted business partners and service providers access to it. Your information is held securely by MTKT Capital and our trusted partners. We may share your basic information (Name, Company Name, Phone, Email Address and Requested Loan Amount) with one of our business partners if we are unable to provide you with a loan.</p></li><hr>
    <li>Security of Information<p>MTKT Capital takes the security of your information very seriously. MTKT Capital protects your information using bank-level data security: 128 bit-encryption and a Secure Sockets Layer (SSL) protocol. This creates an encrypted connection between your browser and our servers. All information remains encrypted at all times.</p><p>If you allow MTKT Capital to see your banking information online rather than in paper form, it is on a read-only basis. We do not have access to change, edit, or modify bank account information in any way. MTKT Capital employees cannot view your banking username and passwords, and we securely store them in separate encrypted areas with our financial services providers.</p></li><hr>
    <li>Opt-Out Policy<p>MTKT Capital and your business partners may contact you to offer you products and services that may of interest to you. To opt-out of receiving emails, telephone solicitations or other forms of contact from MTKT Capital, and our trusted business partners regarding other products and services, please send an email to  with  contact[at]mtktcapital.com , “Opt-Out” in the Subject line, or a letter by postal mail to:</p><address>MTKT Capital, Inc.<br>ATTN: OutReach, Opt-Out<br>1904 Harbor Blvd., Ste 135<br>Costa Mesa, CA 92627<br>USA
            <p>You must include your full name and business mailing email addresses and account number. Once we locate your contact information based on the information you provide us, it will be removed from our databases and mailings lists.</p></address></li></ul>    </p>


@stop